### PR TITLE
Make drop.js comply to strict-di

### PR DESCRIPTION
**Pull request by geremih**
This allows the js file to be minified.

### CODE REVIEW

**Comment by stevenh77** [comment]
Hey @geremih, thanks for the pull request!  Do the karma, protractor test and example pages work for you?

**Comment by geremih** [comment]
Yup, the test is failing on circle because it can't find protractor somehow.

**Comment by stevenh77** [comment]
You can ignore circle, I've taken that off now.

Can you try a clean check out to a new directory as the tests and example pages don't work for me.  When I swap back the drop source file to the previous version everything works fine.

failing

**Comment by stevenh77** [comment]
aha pesky comma eh?! :) merge complete, version bumped and new release now available.  

Thanks again for your contribution!

**Pull request merged**
